plugins {
  id 'com.android.library'
  id 'org.jetbrains.kotlin.android'
}

android {
  namespace 'in.sanketsetu.nearby'
  compileSdk 35

  defaultConfig {
    minSdk 24
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation 'com.google.android.gms:play-services-nearby:19.3.0'
}
